name: Feature Request
description: Suggest a new feature or enhancement for the activities website
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your idea.
  
  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like to add?
      description: Describe the new feature or enhancement in simple terms.
      placeholder: For example, "Add a calendar view so students can see activities organized by day and time"
    validations:
      required: true
  
  - type: textarea
    id: why-needed
    attributes:
      label: Why is this feature needed?
      description: Explain the problem this feature would solve or the benefit it would provide.
      placeholder: For example, "Students are having trouble seeing which activities conflict with their schedule. A calendar view would make it easier to see time overlaps."
    validations:
      required: true
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: How should it work?
      description: Describe how you envision this feature working. Be as specific as possible.
      placeholder: |
        - Add a toggle button to switch between card view and calendar view
        - Calendar shows Sunday through Saturday
        - Activities appear at their scheduled times
        - Students can click on activities to see details
    validations:
      required: true
  
  - type: dropdown
    id: feature-area
    attributes:
      label: Which area of the website would this affect?
      description: Select where this feature should be added.
      options:
        - Homepage/Activities List
        - Activity Details
        - Sign-up/Registration
        - Filters and Search
        - Navigation/Layout
        - New Page/Section
        - Data/Information Display
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature?
      description: Help us understand the priority.
      options:
        - Critical - Blocking students from using the site
        - High - Would significantly improve the experience
        - Medium - Nice to have, would be helpful
        - Low - Small improvement or nice extra feature
    validations:
      required: true
  
  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Provide any examples, mockups, or links to similar features on other websites.
      placeholder: You can paste images, draw simple sketches, or provide links to examples.
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other helpful details or constraints we should know about.
      placeholder: For example, "This should work on both computers and phones" or "Keep it simple for students to use"
    validations:
      required: false
